/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as GravarRouteImport } from './routes/gravar'
import { Route as AtividadesIndexRouteImport } from './routes/atividades.index'
import { Route as AtividadesActivityIdRouteImport } from './routes/atividades.$activityId'
import { Route as TrilhasTrailIdRouteImport } from './routes/trilhas.$trailId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const GravarRoute = GravarRouteImport.update({
  id: '/gravar',
  path: '/gravar',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesActivityIdRoute = AtividadesActivityIdRouteImport.update({
  id: '/atividades/$activityId',
  path: '/atividades/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasTrailIdRoute = TrilhasTrailIdRouteImport.update({
  id: '/trilhas/$trailId',
  path: '/trilhas/$trailId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/gravar': typeof GravarRoute
  '/atividades/$activityId': typeof AtividadesActivityIdRoute
  '/trilhas/$trailId': typeof TrilhasTrailIdRoute
  '/atividades/': typeof AtividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/gravar': typeof GravarRoute
  '/atividades/$activityId': typeof AtividadesActivityIdRoute
  '/trilhas/$trailId': typeof TrilhasTrailIdRoute
  '/atividades': typeof AtividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/gravar': typeof GravarRoute
  '/atividades/$activityId': typeof AtividadesActivityIdRoute
  '/trilhas/$trailId': typeof TrilhasTrailIdRoute
  '/atividades/': typeof AtividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/gravar'
    | '/atividades/$activityId'
    | '/trilhas/$trailId'
    | '/atividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/gravar'
    | '/atividades/$activityId'
    | '/trilhas/$trailId'
    | '/atividades'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/explorar'
    | '/gravar'
    | '/atividades/$activityId'
    | '/trilhas/$trailId'
    | '/atividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  GravarRoute: typeof GravarRoute
  AtividadesActivityIdRoute: typeof AtividadesActivityIdRoute
  TrilhasTrailIdRoute: typeof TrilhasTrailIdRoute
  AtividadesIndexRoute: typeof AtividadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gravar': {
      id: '/gravar'
      path: '/gravar'
      fullPath: '/gravar'
      preLoaderRoute: typeof GravarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$activityId': {
      id: '/atividades/$activityId'
      path: '/atividades/$activityId'
      fullPath: '/atividades/$activityId'
      preLoaderRoute: typeof AtividadesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$trailId': {
      id: '/trilhas/$trailId'
      path: '/trilhas/$trailId'
      fullPath: '/trilhas/$trailId'
      preLoaderRoute: typeof TrilhasTrailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  GravarRoute: GravarRoute,
  AtividadesActivityIdRoute: AtividadesActivityIdRoute,
  TrilhasTrailIdRoute: TrilhasTrailIdRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
